# 开发环境配置
# 数据源配置，请修改为你项目的实际配置
# server config
server:
  port: 8024
  contextPath:
# todo: change to your own datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pricetag_ota?useSSL=false
    username: admin
    password: 90mysql.
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com: debug